// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://soblxtzltnziynrvasaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvYmx4dHpsdG56aXlucnZhc2F3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MTgzNzMsImV4cCI6MjA3MzA5NDM3M30.p22QcK4ky3xSWdMtffiEAiYsviBwmE1VvLE90Zy614o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});